# Generated by Django 3.1.2 on 2020-10-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('classes', models.ManyToManyField(to='evaluations.Class')),
                ('homeroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.teacher')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.house')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.SmallIntegerField(choices=[(1, 'First meeting'), (2, 'Second meeting'), (3, 'Third meeting')])),
                ('evaluation_text', models.TextField()),
                ('evaluated_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.house'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.subject'),
        ),
    ]
