# Generated by Django 3.1.2 on 2020-11-21 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.house')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'house')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hebrew_year', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.house')),
                ('students', models.ManyToManyField(blank=True, to='evaluations.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_text', models.TextField(blank=True, default='')),
                ('hebrew_year', models.IntegerField()),
                ('trimester', models.IntegerField(choices=[(1, 'FIRST_TRIMESTER'), (2, 'SECOND_TRIMESTER'), (3, 'THIRD_TRIMESTER')])),
                ('evaluated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.student')),
            ],
            options={
                'unique_together': {('student', 'evaluated_class', 'trimester')},
            },
        ),
    ]
