# Generated by Django 3.1.2 on 2020-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_auto_20201124_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='trimester',
            field=models.CharField(choices=[('first-trimester', 'FIRST_TRIMESTER'), ('second-trimester', 'SECOND_TRIMESTER'), ('third-trimester', 'THIRD_TRIMESTER'), ('null-trimester', 'NULL_TRIMESTER')], max_length=20),
        ),
    ]
