# Generated by Django 3.1.2 on 2021-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_auto_20210104_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
