# Generated by Django 3.1.2 on 2021-01-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0009_teacher_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pronoun_choice',
            field=models.CharField(choices=[('FEMALE', 'לשון נקבה'), ('MALE', 'לשון זכר'), ('NEUTRAL', 'לשון ניטרלית'), ('MIXED', 'לשון מעורבת')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
