# Generated by Django 3.1.2 on 2021-01-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_auto_20210107_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name')},
        ),
    ]
