# Generated by Django 3.1.2 on 2021-01-08 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0011_auto_20210107_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'hebrew_year', 'teacher')},
        ),
    ]
