# Generated by Django 3.2.25 on 2026-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_house_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
