# Generated by Django 3.2.13 on 2026-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_student_external_id_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
