"""
Django settings for profile_server project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import socket

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^i34c0ernf6maes&z7d=5uk))vq8i^ot!p!qzk@c5-9rx+i%*@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.111', 'localhost', '127.0.0.1']
DOMAIN = 'http://localhost:8000'

# Application definition

INSTALLED_APPS = [
    'evaluations.apps.EvaluationsConfig',
    'accounts.apps.AccountsConfig',
    'class_manager.apps.ClassManagerConfig',
    'dashboard.apps.DashboardConfig',
    'validations.apps.ValidationsConfig',
    'emails.apps.EmailsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'dbbackup',
    'django_email_verification'
]

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/var/profile-db-backups'}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'profile_server.urls'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'profile.democrati.ks@gmail.com'
SERVER_EMAIL = 'profile@democrati.xyz'

DEFAULT_FROM_EMAIL = "מערכת הדיווחים - דמוקרטי כפר סבא" + f" <{EMAIL_HOST_USER}>"

# Fields required by django_email_verification
EMAIL_ACTIVE_FIELD = 'is_active'
EMAIL_SERVER = EMAIL_HOST
EMAIL_ADDRESS = EMAIL_HOST_USER
EMAIL_FROM_ADDRESS = DEFAULT_FROM_EMAIL
EMAIL_PAGE_DOMAIN = DOMAIN
EMAIL_PAGE_TEMPLATE = 'accounts/registration_validated.html'
EMAIL_MAIL_SUBJECT = 'מערכת הדיווחים של הדמוקרטי - אישור הרשמה'
EMAIL_MAIL_HTML = 'emails/registration_verification_email.html'


ADMINS = (
  ('alon aviv', 'alonaviv@gmail.com'),
)

with open('../email-password') as f:
    EMAIL_HOST_PASSWORD = f.read().strip()

EMAIL_PASSWORD = EMAIL_HOST_PASSWORD

try:
    HOSTNAME = socket.gethostname()
except:
    HOSTNAME = 'localhost'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'profile_server.custom_context_processors.trimester_context_processor',
                'profile_server.custom_context_processors.pronoun_dict_context_processor',
                'profile_server.custom_context_processors.teacher_context_processor',

            ],
        },
    },
]

WSGI_APPLICATION = 'profile_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'profile-db',
        'USER': 'postgres',
        'PASSWORD': '76697421',
        'HOST': 'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
    {
        'NAME': 'accounts.custom_validators.HebrewNumericPasswordValidator',
    },
    {
        'NAME': 'accounts.custom_validators.HebrewMinimumLengthValidator',
    },
    {
        'NAME': 'accounts.custom_validators.EnglishCharsValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'profile_server/static')
]


CRISPY_TEMPLATE_PACK="bootstrap4"

LOGIN_URL = '/failed_login'


AUTH_USER_MODEL = 'accounts.TeacherUser'


try:
    from .local_settings import *
except ImportError:
    pass
