# Generated by Django 3.1.2 on 2020-11-23 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.house'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='teacher_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.teacher'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
