# Generated by Django 3.1.2 on 2020-12-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201228_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='pronoun_choice',
            field=models.CharField(choices=[('female', 'לשון נקבה'), ('male', 'לשון זכר'), ('neutral', 'לשון ניטרלית'), ('mixed', 'לשון מעורבבת')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
