# Generated by Django 3.1.2 on 2021-01-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201229_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
