# Generated by Django 3.1.2 on 2021-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_teacheruser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='reminders_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
