# Generated by Django 3.2.13 on 2022-04-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_house_is_deleted'),
        ('accounts', '0012_teacheruser_reminders_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruser',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.house'),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='is_homeroom_teacher',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='pronoun_choice',
            field=models.CharField(blank=True, choices=[('FEMALE', 'לשון נקבה'), ('MALE', 'לשון זכר'), ('NEUTRAL', 'לשון ניטרלית'), ('MIXED', 'לשון מעורבת')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='teacher_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.teacher'),
        ),
    ]
